project:
  type: website

website:
  title: "幻网驭码"
  favicon: favicon.png
  open-graph: true
  navbar:
    left: 
      - text: "友链"
        file: link.qmd
      - text: "镜像站"
        menu:
          - text: "暂时还没有～"
format:
  html:
    theme: cosmo
    css: styles.css



